#!/bin/sh
echo "Generated by Dockerfile"

echo "Variables"
echo SOURCE $SOURCE
echo TEST $TEST

pwd
ls -al .

wget $SOURCE -O main.py
wget $TEST -O test.py

python main.py
python test.py


# echo "Running /app/main.py"
# python /app/main.py

# echo "Running /app/data/main.py"
# python /app/data/main.py